# Generated by Django 5.0.1 on 2024-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
